import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// Components
import Sidebar from "@/components/view/Sidebar";
import Header from "@/components/view/Header";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rfDewi = localFont({
  src: [
    {
      path: "./rf-dewi/RFDewi-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./rf-dewi/RFDewi-SemiBold.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./rf-dewi/RFDewi-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./rf-dewi/RFDewi-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./rf-dewi/RFDewi-Thin.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-dewi",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + rfDewi.variable}>
        <main className="flex min-h-screen">
          <Sidebar />
          <div className="flex flex-col gap-y-1 w-full">
            <Header />
            <Separator orientation="horizontal" className="w-full" />
            <div className="p-3">{children} </div>
          </div>
        </main>
      </body>
    </html>
  );
}
